[package]
name = "helloterm"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.4", features = ["derive"] }
color-eyre = "0.6.3"
crossterm = "0.27.0"
parquet2 = "0.17.2"
ratatui = "0.26.2"
